"""Add subscription to User model

Revision ID: 341b791c4912
Revises: bf0bb15b3842
Create Date: 2024-09-15 23:28:49.776356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341b791c4912'
down_revision = 'bf0bb15b3842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
