"""Add login attempt tracking fields to user model

Revision ID: df9c98758ec2
Revises: 51cebe381736
Create Date: 2024-09-19 23:18:18.219915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c98758ec2'
down_revision = '51cebe381736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lock_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lock_until')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
