"""Added plan field to User model

Revision ID: fc8777ae687a
Revises: 341b791c4912
Create Date: 2024-09-16 13:06:57.545352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8777ae687a'
down_revision = '341b791c4912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=True))
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
